apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqllite-api-sample-deployment
  labels:
    app: sqllite-api-sample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sqllite-api-sample-deployment
  template:
    metadata:
      labels:
        app: sqllite-api-sample-deployment
    spec:
      containers:
       - name: sqllite-api-sample-deployment
         image: registry.cloud.okteto.net/abdallahabuhussein/sqllite-api-sample:latest
         env:
         - name: POD_NAMESPACE
           valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
         resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
         ports:
           - name: nodejs-port
             containerPort: 8080
         livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
         readinessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30