apiVersion: v1
kind: Service
metadata:
  name: sqllite-api-sample-service
  annotations:
    dev.okteto.com/auto-ingress: "domain"
spec:
  ports:
  - port: 8080
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: sqllite-api-sample-deployment
  type: LoadBalancer